---
title: "Fields"
jupyter:
  kernelspec: 
    name: "python3"
    language: python
    display_name: "python3"
code-fold: false
---

## Potential fields

### Definition of a vector field
A vector field $\vb  F : \mathbb R^n \mapsto \mathbb R^n$ defined on a subset $\Omega \subset \mathbb R^n$ assigns to each point $\vb x \in \mathbb R^n$ a vector $\vb F(\vb x) \in \Omega$.

A vector field $\vb F$ is a _potential_ or _conservative vector field_ if and only if there exists a scalar field $\Phi: \mathbb R^n \mapsto \mathbb R$ such that it holds $\vb F (\vb x) = \grad \Phi(\vb x)$.

### Equivalent properties of conservative fields
- The line integral $\int_C$ along any curve $C$ within the field only depends on the start and the end points, but not on the path between them (_path independence_)

- The closed line integral is zero for any curve $C$: $\oint_C \grad \Phi(\vb x ) \cdot \dd{\vb x} = \oint \vb F (\vb x ) \cdot \dd{\vb x} = 0$

- Such vector fields are curl free (irrotational), i.e., $\curl \grad \Phi(\vb x ) = \curl \vb F (\vb x ) \equiv \vb 0$

### Divergence theorem

Statements about the sources and sinks of vector fields can be derived by applying the divergence theorem.

The dielectric displacement $\vb D = \varepsilon(\vb x) \vb E(\vb x)$ has its sources in a volume density of electric charges $\rho_E (\vb x)$.

It holds

$\rho_E = \div \vb D = - \div (\varepsilon \grad \Phi).$

For homogeneous dielectrics we obtain the _Poisson equation of electrostatics_ 

$-\Delta \Phi = \rho_E/\varepsilon.$



### Poisson equation
Potential theory attempts to calculate the unknown potential (the *potential function*) $\Phi$ caused by a given physical quantity, e.g., a source distribution $\rho(\vb x)$.

  The potential function can generally be determined by **integrating** the Poisson equation.

  Often, only its spatial derivative is desired, because for physicists only the fields are a meaningful quantity.

### Laplace equation
In a region where sources are absent, i.e., $\rho(\vb x ) \equiv 0$, the Poisson equation becomes the Laplace equation
  
$\Delta \Phi(\vb x) = 0$

with the scalar function $\Phi$ (the _potential_) defined over a subset $\Omega \subset \mathbb R^n$.

This elliptic partial differential equation (or short, the _potential equation_) is the point of departure in the potential theory.


### Mathematical Tools
The potential theory makes use of the _functional analysis_ and its tools, e.g., 

-  vector spaces
-  inner product 
-  norm
-  differentiability
-  continuity
  
  etc.

::: {.callout-tip title="Spaces"}

We consider _spaces_ with a norm induced by the _inner product_.

  *Euclidean space*: Any vector space defined over $\mathbb R^n$ equipped with an inner product of any finite dimension is called _Euclidean vector space_.

  The coordinate space $\mathbb R^3$ with standard dot product is a Euclidean space!

  *Hilbert space:* A Hilbert space is a vector space $H$ with an inner product $\langle f,g \rangle$ such that the norm $|f| = \langle f,f \rangle^{1/2}$ turns the space into a complete metric space.

  The coordinate spaces $\mathbb R^n$ and $\mathbb C^n$ are Hilbert spaces!

:::

::: {.callout-tip title="Scalar product"}

With $\vb x = (x_1, x_2, \dots, x_n)^\top$ we denote an $n$-tuple of numbers or a _point_ in $\mathbb R^n$, and define the  *scalar product* in $\mathbb R^n$ given by the dot product 
  
$$
\langle \cdot,\cdot \rangle : \mathbb R^n \mapsto \mathbb R,
$$ 
e.g.,
$$
\langle \vb x , \vb y \rangle = \sum_{i=1}^n x_i y_i
$$
as well as the *norm induced by the inner product*
$$
x = \abs{\vb x} = \langle \vb x , \vb x  \rangle^{1/2}
$$
The norm $\abs{\cdot} : \mathbb R^n \mapsto \mathbb R$, as a function, assigns to $\vb x$ its length.

:::



::: {.callout-tip title="Differentiation"}

Let $\Omega \subset \mathbb R^n$ be an open subset. 

A _derivative of order_ $\vb \alpha$ is defined by a differential operator $D: C^k (\Omega) \mapsto C(\Omega)$ represented by

$D^{\vb \alpha} f(\vb x) = \dfrac{\partial^{|\vb \alpha|} f(x_1, x_2, \dots, x_n)}{\partial x_1^{\alpha_1} \partial x_2^{\alpha_2}\, \dots \,\partial x_n^{\alpha_n}}$

and a _multi-index_
$\vb(\alpha = (\alpha_1, \alpha_2, \dots, \alpha_n) \in \mathbb N_0^n$ with $|\vb\alpha| = \sum_{i=1}^n \alpha_i$.

Other notations derived from the above definition are:

- $f_x := \pdv{f}{x}$ where $n=1, \alpha_1=1, |\vb\alpha|=1$

- $f_{x x} := \pdv[2]{f}{x}$ where $n=1, \alpha_1=2, |\vb\alpha|=2$

- $f_{x z} := \pdv{f}{x}{z}$ where $n=3, \alpha_1=1, \alpha_2=0, \alpha_3=1, |\vb\alpha||=2$

:::

::: {.callout-tip title="Differentiability classes"}

What is $C^k(\Omega)$?

The space of the continuous real valued functions in a domain $\Omega$ is of class $C(\Omega)$ or $C^0(\Omega)$.

This space contains all differentiable functions in $\Omega \subset \mathbb R^n$.

Functions whose (partial) derivatives are also continuous are called continuously differentiable.
These functions are said to be of class $C^1(\Omega)$.

Correspondingly, $C^n (\Omega)$ is called the space of the functions which are $n$-differentiable, where the $n$-th derivative $D^{\vb\alpha} f(\vb x), |\vb\alpha| \le n$ is continuous on $\Omega$.

Arbitrarily often differentiable (smooth) functions belong to $C^\infty ( \Omega)$.

:::

::: {.callout-tip  title="Harmonic function"}

We define the _harmonic function_:

A real-valued function $U(\vb x) \in C^2 (\Omega)$ is called _harmonic_ or _regular potential function_ in the subset $\Omega \subset \mathbb R^n$ if there holds

$$
\Delta U(\vb x) = 0
$$

for $\vb x \in \Omega$.

:::

## Solution of the Laplace and Poisson equations

We consider the second-order differential equations

::: {.callout-tip title="Laplace equation"}
$$
\dv[2]{y}{x} = 0
$$
:::

and 

::: {.callout-tip title="Poisson equation"}
$$
\dv[2]{y}{x} = -4\cos(4x) - 8 \sin(8 x)
$$
:::

for $x \in [0, 1]$ subject to the boundary conditions $y(0)=1$ and $y(1)=0$.

To obtain the solution to the above PDEs, we employ the `Python` package `sympy`, which is a powerful library for symbolic mathematics.

Symbolic functions which depend on symbolic variables have to be defined with the function `Function`.

The solution of the differential equations can be obtained by a call to the `dsolve` function.

The signature of the function can be understood as follows:

-   Solve the symbolic equation given by the expressions `eq_poisson` and `eq_laplace`, resp.
-   The desired solution is `y(x)`
-   Boundary conditions can be enforced by the values following the keyword `ics`. In the example, `y(0)=1` and `y(1)=0`.

```{python}
#| code-fold: true
from sympy import Function, dsolve, diff, cos, sin
from sympy.abc import x
from sympy.plotting import plot, PlotGrid
import matplotlib.pyplot as plt
# plt.style.use('fivethirtyeight')

y = Function('y')
eq_poisson = diff(y(x), x, 2) + 4 * cos(4 * x) + 8 * sin(8 * x)
eq_laplace = diff(y(x), x, 2)
result_poisson = dsolve(eq_poisson, y(x), ics={y(0): 1, y(1): 0})
result_laplace = dsolve(eq_laplace, y(x), ics={y(0): 1, y(1): 0})
p1 = plot(result_poisson.rhs, (x, 0, 1), 
      ylim=(-0.2, 1.2), 
      ylabel='y(x)', 
      axis_center='auto',
      show=False,
      title='Poisson equation');
p2 = plot(result_laplace.rhs, (x, 0, 1), 
      ylim=(-0.2, 1.2), 
      ylabel='y(x)', 
      axis_center='auto',
      show=False,
      title='Laplace equation');
PlotGrid(1, 2, p1, p2, size=(7,3));
```
## What can be observed in the 1-D case?

-   The solution of the *Laplace equation* does not exhibit local extrema
    -   It has no curvature
-   The solution of the *Poisson equation* has local minima and maxima
    -   Its extrema might get larger or smaller than those of the Dirichlet values at the boundary