---
title: "Potential of a magnetic dipole"
jupyter: python3
---

The magnetic field $\mathbf{B}$ is curl-free outside the source distribution
$$
\nabla \times \mathbf{B} = \mathbf{0}
$$
and has a potential
$$
\mathbf{H} = - \nabla \Psi.
$$

The potential $\Psi$ satisfies the Laplace equation 
$$
\Delta \Psi = 0
$$
since it holds $\nabla \cdot \mathbf{B} = 0$.

## Derivation

Induction:
$$
\mathbf{B} = \mu_{r} \mu_{0} \mathbf{H} = \mu_{0}(\mathbf{H} + \mathbf{M}) = \mu_{0}\mathbf{H} + \mathbf{J}
$$
where $\mathbf{J}$ is the magnetic polarization.

Potential:
$$
\begin{align}
\Psi(\mathbf{r}) & = -\frac{1}{4 \pi} \mathbf{m} \cdot \nabla \frac{1}{| \mathbf{r} - \mathbf{r'}|} \\
& = \frac{1}{4 \pi} \mathbf{m} \cdot \frac{\mathbf{r} - \mathbf{r'}}{| \mathbf{r} - \mathbf{r'}|^{3}}.
\end{align}
$$

If $\mathbf{m} = (0, 0, m)^\top$ and $\mathbf{r'} = (0, 0, 0)^\top$, we refer to a vertical magnetic dipole at the origin. Then, with $r = |\mathbf{r}|$:
$$
\Psi(\mathbf{r}) = \frac{m}{4 \pi} \frac{z}{r^{3}} = \frac{m}{4 \pi} \frac{\cos \theta}{r^{2}}.
$$

## Magnetic Field

The magnetic field is given by:
$$
\begin{align}
\mathbf{H} & = - \nabla \Psi \\
& = -\frac{m}{4 \pi} \left( \hat{\mathbf{r}} \frac{\partial}{\partial r} + \frac{1}{r} \hat{\theta} \frac{\partial}{\partial \theta} + \frac{1}{r \sin \theta} \hat{\phi} \frac{\partial}{\partial \phi} \right) \frac{\cos \theta}{r^{2}} \\
& = +\frac{m}{4 \pi} \left( \hat{\mathbf{r}} \frac{2 \cos \theta}{r^{3}} + \hat{\theta} \frac{\sin \theta}{r^{3}} \right) \\
& = (H_{r}, H_{\theta}, 0)^\top.
\end{align}
$$

The magnitude of the field is:
$$
H = \sqrt{H_{r}^{2} + H_{\theta}^{2}} = \frac{m}{4 \pi r^{3}} \sqrt{1 + 3 \cos^{2} \theta}.
$$

The field strength decreases as $r^{-3}$, and the field direction depends on the angle $\theta$.

The magnitude of the field along the dipole axis is twice as large as that in the equatorial plane. At $\theta = 0$ and $\theta = \frac{\pi}{2}$, one of the components of $\mathbf{H}$ vanishes. These positions are known as the _Gauss first_ and _second principal axes_, respectively.


## Spatial Distribution of the Dipole Moment

Dipole density: Magnetization corresponds to the density of dipole moments:
$$
\mathbf{m} = \int_{V} \mathbf{M} \, \mathrm{d}{^3\vb r}.
$$

Substituting the dipole moment into the potential equation gives:
$$
\Psi(\mathbf{r}) = -\frac{1}{4 \pi} \int \mathbf{M} \cdot \nabla \frac{1}{|\mathbf{r} - \mathbf{r'}|} \, \mathrm{d}{^3\vb r}.
$$

For homogeneous magnetization:
$$
\Psi(\mathbf{r}) = -\frac{1}{4 \pi} \mathbf{M} \cdot \nabla \int \frac{1}{|\mathbf{r} - \mathbf{r'}|} \, \mathrm{d}{^3\vb r}.
$$

:::{.callout-note title="The Poisson-Eötvös relation"}

We depart from the magnetic potential $\Psi$
$$
\Psi(\vb{r}) = -\frac{1}{4 \pi} \grad \cdot \int \vb{M} \frac{1}{|\vb{ r}|} \, \dd {^3\vb r}.
$$
In the case of a homogeneous magnetization we write
$$
\Psi(\vb{r}) = -\frac{1}{4 \pi} \vb{M} \cdot \grad  \int \frac{1}{|\vb{ r}|} \, \dd {^3\vb r}
$$
Recall the gravitational potential 
$$
V(\vb{r}) = f \rho \int \frac{1}{|\vb{r}|} \, \dd {^3\vb r}
$$
which we insert into the magnetic dipole potential to obtain
$$
\Psi(\vb{r}) = -\frac{1}{4 \pi} \frac{\vb{M}}{f \rho} \cdot \grad V(\vb{r}).
$$
This is the _Poisson formula_.
In a Cartesian coordinate system we write for the partial derivatives
$$
V_{x} = \frac{ \partial V (\vb r)}{ \partial x} \text{ etc.} 
$$
and
$$
\vb{M} = (M_{1}, M_{2}, M_{3})^\top. 
$$
Now, with
$$
\Psi(\vb r) = -\frac{1}{4 \pi f \rho}(M_{1}V_{x}(\vb r) + M_{2}V_{y}(\vb r) + M_{3}V_{z}(\vb r))
$$

and
$$
\vb{B}(\vb r) = -\mu_{0}\grad \Psi(\vb r)
$$
we obtain
$$
\begin{align}
B_{x}(\vb r) &= \frac{\mu_{0}}{4 \pi f \rho} (M_{1}V_{xx}(\vb r) + M_{2}V_{yx}(\vb r) + M_{3}V_{zx}(\vb r)) \\
B_{y}(\vb r) &= \frac{\mu_{0}}{4 \pi f \rho} (M_{1}V_{xy}(\vb r) + M_{2}V_{yy}(\vb r) + M_{3}V_{zy}(\vb r)) \\ 
B_{z}(\vb r) &= \frac{\mu_{0}}{4 \pi f \rho} (M_{1}V_{xz}(\vb r) + M_{2}V_{yz}(\vb r) + M_{3}V_{zz}(\vb r))
\end{align}
$$
We introduce the _Poisson-Eötvös tensor_
$$
\tilde{G} = \tilde{G}(\vb r) = \frac{\mu_{0}}{4 \pi f \rho} 
\begin{pmatrix}
V_{x x} & V_{xy} & V_{xz} \\
V_{y x} & V_{yy} & V_{yz} \\
V_{z x} & V_{zy} & V_{zz}
\end{pmatrix}
$$
and get
$$
\vb{B} = \tilde{G} \vb{M}.
$$
It is therefore possible to calculate the components of the magnetic anomaly of a body with homogeneous magnetization by providing the second-order partial derivatives of the gravitational potential of the same body with assumed homogeneous mass density.

:::

## Magnetic Dipole

```{python}
import numpy as np
import matplotlib.pyplot as plt
from sympy import *
```

For the dipole field of a magnetized sphere at position $\mathbf{r'}$ with dipole moment $\mathbf{m}$:
$$
\mathbf{B}(\mathbf{r}) = \frac{\mu_{0}}{4 \pi R^5} \left( 3 (\mathbf{m}^\top (\mathbf{r} - \mathbf{r'})) (\mathbf{r} - \mathbf{r'}) - \mathbf{m} R^2 \right).
$$

### Derivation using `SymPy`

```{python}
m_x, m_y, m_z, x, y, z, mu = symbols('m_x m_y m_z x y z mu_0', real=True)
r = symbols('r', positive=True)
m = Matrix([m_x, m_y, m_z])
V = -mu / 4 / pi * m.dot([diff(1 / sqrt(x**2 + y**2 + z**2), q) for q in [x,y,z]])
V
```

The field can be obtained by taking the negative gradient of the potential:

```{python}
B = [-diff(V, p) for p in [x,y,z]]
simplify(Matrix([B[0], B[1], B[2]])).subs(x**2+y**2+z**2, r**2)
```

This result can be rewritten in compact form as
$$
\mathbf{B}(\mathbf r)= \frac{\mu_0}{4 \pi r^3} 
\left(3({\mathbf{m}} \cdot {\hat{\mathbf{r}}}) {\hat{\mathbf{r}}}-{\mathbf{m}}\right)
$$
with the radial unit vector
$$
\hat{\mathbf r} = \frac{\mathbf r}{r}, \quad r = |\mathbf r|.
$$


The induced magnetization is caused by the magnetic field within the body:
$$
\mathbf{M}_{i} = (\mu_{r} - 1) \mathbf{H} = \kappa \mathbf{H} = \frac{\kappa}{\mu_{0}} \mathbf{B}.
$$

The susceptibility $\kappa$ is obtained from the magnetic permeability:
$$
\mu = \mu_{0} \mu_{r} = \mu_{0}(1 + \kappa),
$$
hence:
$$
\kappa = \mu_{r} - 1.
$$

The susceptibility is a dimensionless quantity, typically expressed in $10^{-5}$ SI units.

The dipole moment of a sphere with radius $a$ and susceptibility $\kappa$ in the geomagnetic main field $\mathbf{T_{0}}$ is:
$$
\mathbf{m} = \frac{\kappa}{\mu_{0}} \mathbf{T_{0}} \frac{4 \pi}{3} a^{3}.
$$