# Point mass

We introduce _point sources_.

However, the difficulty is that, e.g., for a point mass there is no proper definition of a density in the sense of a _mass per volume_.

Difficulties arise when we have to integrate the Poisson's equation with point sources.

To this end, we introduce a generalized function with the desired property that it provides finite integral values for unbounded integrands.

We define

$$
\delta(\vb x) = \lim_{\epsilon \to 0} h_{\epsilon}(\vb x) = 
\begin{cases}
\infty  & \qif \vb x = \vb 0 \\
0 & \qif \vb x \ne \vb 0
\end{cases}
$$
with the function
$$
h_{\epsilon}(\vb x) = 
\begin{cases}
\frac{3}{4 \pi \epsilon^3}  & \qif |\vb x| \le \epsilon \\
0 & \qif |\vb x| \gt \epsilon 0
\end{cases}
$$
which describes a unit mass distributed over a small sphere of ardius $\epsilon$.

$\delta(\vb x)$ is the limit of the sequence of functions $h_\epsilon(\vb x)$ for $\epsilon \to 0$.

We are now able to evaluate the density of the sphere as $\rho(\vb x) = m h_\epsilon(\vb x)$.

Further, the integral over a domain $G$ containing the point $\vb x$ is finite, i.e.,

$$
\int_G h_\epsilon(\vb x) \, \dd {\vb x} = 1.
$$

We calculate the _weak limit_ of the function sequence $h_\epsilon(\vb x)$ for $\epsilon \to 0$ and any continuous test function $\Phi(\vb x)$

$$
\lim_{\epsilon \to 0} \int \Phi(\vb x) h_\epsilon(\vb x) \, \dd {\vb x} = \Phi(0)
$$

The functional which assigns to each continuous function $\Phi(\vb x)$ its value at the point $\vb x = 0$, i.e., $\Phi(0)$, is called the _weak limit_ of the function $h_\epsilon(\vb x), \epsilon \to 0$.
This functional can be used to define the density $\delta(\vb x)$.

It holds
$$
\int_G \delta(\vb x) \, \dd {\vb x} = 1 \qif \vb x = \vb 0 \in G.
$$
